import React from 'react'
import type { Metadata } from 'next'

import { Be_Vietnam_Pro } from 'next/font/google'
import './globals.css'

import Header from '../components/Header'
import Footer from '../components/Footer'
import Providers from '../providers'

const font = Be_Vietnam_Pro({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'CineNow',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
